"project_id" : "2"
"base_path" : "."
"base_url" : "https://berty.crowdin.com"

"commit_message": 'fix(i18n): new %language% translations


Signed-off-by: Berty Assistant <22729528+berty-assistant@users.noreply.github.com>
'

"append_commit_message": false
"preserve_hierarchy": true

files: [
 {
  "source" : "/js/packages/berty-i18n/locale/en-US/messages.json",
  "translation" : "/js/packages/berty-i18n/locale/%locale%/%original_file_name%",
 }
]
