peer:
    - name: peers
      amount: 2
      daemon:
          - name: group1
            tests:
                - type: text
                  size: 4KB
                  interval: 3
      connections:
          - name: connection
            to: internet
            protocol: tcp
          - name: thing
            to: lan
            protocol: udp

peer:
    - name: test peers 1
      amount: 2
      groups:
      - name: message group
        tests:
        - type: text
          size: 40KB
          interval: 2
      - name: mg 1
        tests:
            - type: text
              size: 40KB
              interval: 1
      connections:
        - name: connection
          to: internet
          protocol: tcp
        - name: thing
          to: lan
          protocol: udp

      routers:
        - type: rdvp
          address: test rdvp

#relay:
#    - name: test relay
#      amount: 1
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
#
#bootstrap:
#    - name: test bs
#      amount: 1
#      connections:
#          - name: connection
#            to: internet
#            protocol: tcp
#      routers:
#          - type: rdvp
#            address: test rdvp
#          - type: relay
#            address: test relay
